/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author artairg
 */
public class AltaDepartamentosVista extends javax.swing.JFrame {

    /**
     * Creates new form AltaDepartamentosVista
     */
    public AltaDepartamentosVista() {
        initComponents();
        Conexion.CrearBD();
        lblInfo.setText("Iniciado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dept_Nombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtLocalidad = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("dept_no");

        dept_Nombre.setText("dept_nombre");

        jLabel3.setText("Localidad");

        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnMod.setText("Mod");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnBaja.setText("Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        jLabel4.setText("Info:");

        lblInfo.setText("Sin inicar");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dept_Nombre)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtNumero)
                                    .addComponent(txtNombre))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAlta)
                            .addComponent(btnMod)
                            .addComponent(btnBaja)
                            .addComponent(btnListar))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dept_Nombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMod))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaja))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblInfo)
                    .addComponent(btnListar))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost
        /*Cuando pierde el focus el cuadro de numero(en el departamento)
        A traves de la consulta GetDepartamento*/
        try {
            if (!txtNumero.getText().isEmpty()) {/*Si hay algo en el numero de departamento*/
                ResultSet SetResultados = Controlador.Consultas.GetDepartamento(Integer.parseInt(txtNumero.getText()));
                if (SetResultados.next()) {/*Si hay resultado*/
                    txtNombre.setText(SetResultados.getString(2));
                    txtLocalidad.setText(SetResultados.getString(3));
                } else {/*Se ponen vacios los cuadrados si no hay resultado*/
                    txtNombre.setText("");
                    txtLocalidad.setText("");
                }
            } else {/*Si el cuadro esta vacio pone los resultados en vacio*/
                txtNombre.setText("");
                txtLocalidad.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AltaDepartamentosVista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtNumeroFocusLost

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        try {
            if (txtNombre.getText().isEmpty() || txtLocalidad.getText().isEmpty() || txtNumero.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Falltan datos!");
            } else {
                Controlador.Consultas.InsertDepartamento(Integer.parseInt(txtNumero.getText()), txtNombre.getText(), txtLocalidad.getText());
                lblInfo.setText("Alta correcta");
            }
            btnListarActionPerformed(evt);/*Para listar automaticamente cada vez que se presiona un boton*/
        }catch (UnsupportedOperationException UO){
            lblInfo.setText("Error Clave Duplicada!");
        } catch (Exception e) {
            lblInfo.setText("Error Revisa la consola!");
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        /*darle vueltas*/
        try {
            if (txtNombre.getText().isEmpty() || txtLocalidad.getText().isEmpty() || txtNumero.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Falltan datos!");
            } else {
                Controlador.Consultas.UpdateDepartamento(Integer.parseInt(txtNumero.getText()), txtNombre.getText(), txtLocalidad.getText());
                lblInfo.setText("Modificacion correcta");
            }
            btnListarActionPerformed(evt);/*Para listar automaticamente cada vez que se presiona un boton*/
        } catch (SQLException ex) {
            lblInfo.setText("Error Revisa la consola!");
            Logger.getLogger(AltaDepartamentosVista.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnModActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        /*Darle vuetlas*/
        try {
            if (txtNumero.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Faltan datos!");
            } else {
                if(Controlador.Consultas.DeleteDepartamento(Integer.parseInt(txtNumero.getText()))!=0){
                    lblInfo.setText("Baja correcta");
                }
            }
            btnListarActionPerformed(evt);/*Para listar automaticamente cada vez que se presiona un boton*/
        } catch (SQLException ex) {
            lblInfo.setText("Error Revisa la consola!");
            Logger.getLogger(AltaDepartamentosVista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        try {
            String Texto = "";
            txtArea.setText("");
            ResultSet SetResultados = Controlador.Consultas.VerEDepartamentos();
            while (SetResultados.next()) {
                Texto = Texto + "Dep nº " + SetResultados.getString(1) + " --- Nombre Dep:" + SetResultados.getString(2) + " --- Localidad: " + SetResultados.getString(3) + "\n";
//                System.out.println("Dep nº " + SetResultados.getString(1) + " --- Nombre Dep:" + SetResultados.getString(2) + " --- Localidad: " + SetResultados.getString(3));
            }
            txtArea.setText(Texto);
        } catch (SQLException ex) {
            lblInfo.setText("Error Revisa la consola!");
            Logger.getLogger(AltaDepartamentosVista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaDepartamentosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaDepartamentosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaDepartamentosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaDepartamentosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaDepartamentosVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnMod;
    private javax.swing.JLabel dept_Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtLocalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables

}
